sonar.projectKey=sw5005-sus_ceramicraft-customer-support-agent-ui
sonar.organization=sw5005-sus
sonar.projectName=ceramicraft-customer-support-agent-ui

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,src/types/**
sonar.coverage.exclusions=src/main.ts,src/types/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
