sonar.projectKey=sw5005-sus_ceramicraft-customer-support-agent-ui
sonar.organization=sw5005-sus
sonar.projectName=ceramicraft-customer-support-agent-ui

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.sourceEncoding=UTF-8
