name: Snyk

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          mkdir -p sarif-reports
          snyk test --severity-threshold=high --sarif-file-output=sarif-reports/snyk-ui.sarif

      - name: Upload Snyk SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: sarif-reports/snyk-ui.sarif

      - name: Snyk monitor
        run: snyk monitor
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
